;Prueba de atom
atom a = 5

;Prueba galaxy
galaxy b = "AstroNova"

;Prueba exist
exist c = true

;asignacion de valores
atom x = 0
atom y = 5
x=y

;expresion matematica
atom expresion = 3 - 2 * 10

imprimir(b)
imprimir("Imprimir AstroNova")

leer.Cad(b)